### ISSUE TITLE
Is this a fork of flutter_interactive_keyboard without credits?

### ISSUE THREAD

**Issue by CavalcanteLeo** [jonataslaw/ikeyboard#1]
ref: https://github.com/mcrovero/flutter_interactive_keyboard/tree/master/ios/Classes

**Comment by jonataslaw** [comment]
Definitely not.
I think this question can be answered by looking at the source code.
iKeyboard implements the iOS InteractiveKeyboard, using native apis and native metrics, the plugin of link is just a hack that makes a screenshot of the keyboard view and displays it.
There isn't a single similar line of code, nor approach.
